# Generated by Django 6.0.5 on 2026-05-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_heading', models.CharField(default='NO CONSULTANCY FEES CHARGED DIRECT MBBS ADMISSION ABROAD', max_length=255)),
                ('hero_subheading', models.TextField(default='Get direct admission assistance for MBBS abroad through official university tie-ups. No hidden charges. No middleman fees.')),
                ('warning_heading', models.CharField(default='⚠️ Important Notice to Students & Parents', max_length=255)),
                ('warning_text', models.TextField(default='Do not pay extra money to agents or middlemen to secure your dream university admission.')),
                ('phone_number', models.CharField(default='+91 98765 43210', max_length=20)),
                ('whatsapp_number', models.CharField(default='919876543210', max_length=20)),
                ('email', models.EmailField(default='info@mbbsnation.com', max_length=254)),
                ('address', models.CharField(default='New Delhi, India', max_length=255)),
                ('instagram_link', models.URLField(blank=True, default='https://instagram.com/mbbsnation', null=True)),
                ('footer_about_text', models.TextField(default='We help Indian students secure direct admission in top MBBS universities abroad without charging consultancy fees.')),
                ('footer_disclaimer', models.TextField(default='Disclaimer: Admission process depends on university eligibility and NEET qualification requirements.')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('total_fees', models.CharField(help_text='e.g., 18,00,000 INR', max_length=100)),
                ('medium', models.CharField(default='English', max_length=50)),
                ('duration', models.CharField(default='6 Years', max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='universities/')),
                ('is_top_destination', models.BooleanField(default=False, help_text='Show on homepage as top destination country card?')),
            ],
        ),
        migrations.AlterField(
            model_name='lead',
            name='preferred_country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
