# Generated by Django 5.0 on 2026-05-12 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_sitecontent_university_alter_lead_preferred_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='about',
            field=models.TextField(blank=True, help_text='Detailed overview of the university', null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='student_facilities',
            field=models.TextField(blank=True, help_text='Details about hostels, mess, sports, etc. You can use simple text or HTML list.', null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='university',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='UniversityImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='universities/gallery/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='api.university')),
            ],
        ),
    ]
