# Generated by Django 5.0 on 2026-05-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_university_about_university_student_facilities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='intake',
            field=models.CharField(default='Sept / Feb', help_text='Admission intake months, e.g. Sept / Feb', max_length=100),
        ),
        migrations.AddField(
            model_name='university',
            name='recognition',
            field=models.CharField(default='WHO, NMC', help_text='Recognition bodies, e.g. WHO, NMC, ECFMG', max_length=255),
        ),
    ]
